version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deploy/scripts/start_docker.sh
      timeout: 300
      runas: root